# Generated by Django 4.2.3 on 2023-09-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='materials_provided',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
